server:
  port: 8088

guns:
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
  file-upload-path: d:/tmp     #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

#spring:
#  datasource:
#   url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: 123456
#    filters: wall,mergeStat

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sun
    password: sun
    validationQuery: select 1 from dual
  #id-ty
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#  redis:
#    password: 123456
#    sentinel:
#      master: T1
#      nodes: 47.101.155.121:16379,47.101.155.121:16380,47.101.155.121:16381
#
    
logging:
  level: 
    root: info
##多数据源情况的配置
#guns:
#  muti-datasource:
#    open: false
#    url: jdbc:mysql://127.0.0.1:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
#    username: root
#    password: root
#    dataSourceNames:
#    - dataSourceGuns
#    - dataSourceBiz