######################################################################
############################ 开发环境配置 ############################
######################################################################

debug: true
#输出当前项目下debug级别的日志
logging:
  level:
    cn.newcapec.busniess: debug
    org.springframework.security: debug

############################ 下面是springBoot配置 ############################
spring:
  thymeleaf:
    cache: false #thymeleaf模板配置，禁用缓存
  redis: #单机redis，开发环境
    host: 192.168.112.44
    port: 6379
    #Lettuce客户端，与jedis客户端有区别,参考: http://baijiahao.baidu.com/s?id=1600235995436023983&wfr=spider&for=pc
    lettuce:
      pool: #redis线程池配置
        maxIdle: 0 #最大空闲数
        minIdle: 0 #最小空闲数
        maxActive: 50 #最大活跃数

############################ 上面是springBoot配置 ############################

############################ 下面是用户自定义配置 ############################
application:
  user:
    onlineno:
      initOddfare: 100 #用户注册的初始化余额，单位（元）
      initPwd: 888888 #用户注册时的初始化密码
  file:
    apk: /newcapec/jtbqrcode/apk/ #APK安装包存放位置
  pay:
    recharge: #充值订单的数据
      name: 新开普二维码充值 #商品名称
      describ: 通过颍州通APP进行账户充值 #商品描述
      minLimit: 1 #充值的最小限额，单位分
  swagger: #swapper相关配置
    enable: true #是否启用swapper

############################ 上面是用户自定义配置 ############################